name: datahub
version: '3.0'
summary: hello
description: hello
grade: devel
confinement: devmode

apps:
  say-hello:
    command: bin/say-hello

parts:
  say-hello:
    plugin: python
    python-version: python3
    source: https://github.com/friedmanss/hello-snap.git
    source-branch: master
